version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.example

  server:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env.example

  client:
    build: './client'
    depends_on:
      - server
    ports:
      - "8001:8001"

  nginx:
    image: nginx:1.23.2-alpine
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    env_file:
      - .env.example
