"""Add models

Revision ID: 291a08212c0c
Revises: 
Create Date: 2023-07-07 02:53:09.827984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291a08212c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('text', sa.String(length=16), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
